author: zedderek
email: zedderek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My progress from scratch to god knows where. Help! I'm stuck.

# social links
# twitter_username: your-twitter-handle
github_username:  zedderek

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
